name: ecoseva_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  dio: ^5.0.3
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^5.4.0
  flutter_riverpod: ^2.3.2
  flutter_secure_storage: ^8.0.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  pie_chart: ^5.3.2
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.3.2
  riverpod_lint: ^1.1.6
  build_runner: ^2.3.3
  flutter_gen: ^5.2.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  # colors:
  #   inputs:
  #     - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay-Bold.otf
          weight: 700
        - asset: assets/fonts/ClashDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/ClashDisplay-Light.otf
          weight: 200
        - asset: assets/fonts/ClashDisplay-Regular.otf
          weight: 400
        - asset: assets/fonts/ClashDisplay-ExtraLight.otf
          weight: 100
        - asset: assets/fonts/ClashDisplay-Semibold.otf
          weight: 600
